name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake-build
      run: cmake CMakeLists.txt
    - name: make
      run: make

  release:
    needs: build  # This job will run only after the build job completes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ runner.os }}-v${{ github.run_number }}
        artifacts: "CI_CD_Example, *"
        body: "Release with CI/CD"
        
